/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyerDealsRouteImport } from './routes/buyer.deals'
import { Route as BuyerDashboardRouteImport } from './routes/buyer.dashboard'
import { Route as BuyerClientsRouteImport } from './routes/buyer.clients'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSupermarketsRouteImport } from './routes/admin.supermarkets'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminDealsRouteImport } from './routes/admin.deals'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as BuyerDealsIndexRouteImport } from './routes/buyer.deals.index'
import { Route as BuyerDealsNewRouteImport } from './routes/buyer.deals.new'

const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDealsRoute = BuyerDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerDashboardRoute = BuyerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerClientsRoute = BuyerClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => BuyerRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupermarketsRoute = AdminSupermarketsRouteImport.update({
  id: '/supermarkets',
  path: '/supermarkets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const BuyerDealsIndexRoute = BuyerDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyerDealsRoute,
} as any)
const BuyerDealsNewRoute = BuyerDealsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BuyerDealsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/buyer': typeof BuyerRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/supermarkets': typeof AdminSupermarketsRoute
  '/admin/team': typeof AdminTeamRoute
  '/auth/login': typeof AuthLoginRoute
  '/buyer/clients': typeof BuyerClientsRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/deals': typeof BuyerDealsRouteWithChildren
  '/buyer/deals/new': typeof BuyerDealsNewRoute
  '/buyer/deals/': typeof BuyerDealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/buyer': typeof BuyerRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/supermarkets': typeof AdminSupermarketsRoute
  '/admin/team': typeof AdminTeamRoute
  '/auth/login': typeof AuthLoginRoute
  '/buyer/clients': typeof BuyerClientsRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/deals/new': typeof BuyerDealsNewRoute
  '/buyer/deals': typeof BuyerDealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/buyer': typeof BuyerRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/supermarkets': typeof AdminSupermarketsRoute
  '/admin/team': typeof AdminTeamRoute
  '/auth/login': typeof AuthLoginRoute
  '/buyer/clients': typeof BuyerClientsRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/deals': typeof BuyerDealsRouteWithChildren
  '/buyer/deals/new': typeof BuyerDealsNewRoute
  '/buyer/deals/': typeof BuyerDealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/buyer'
    | '/admin/dashboard'
    | '/admin/deals'
    | '/admin/products'
    | '/admin/supermarkets'
    | '/admin/team'
    | '/auth/login'
    | '/buyer/clients'
    | '/buyer/dashboard'
    | '/buyer/deals'
    | '/buyer/deals/new'
    | '/buyer/deals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/buyer'
    | '/admin/dashboard'
    | '/admin/deals'
    | '/admin/products'
    | '/admin/supermarkets'
    | '/admin/team'
    | '/auth/login'
    | '/buyer/clients'
    | '/buyer/dashboard'
    | '/buyer/deals/new'
    | '/buyer/deals'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/buyer'
    | '/admin/dashboard'
    | '/admin/deals'
    | '/admin/products'
    | '/admin/supermarkets'
    | '/admin/team'
    | '/auth/login'
    | '/buyer/clients'
    | '/buyer/dashboard'
    | '/buyer/deals'
    | '/buyer/deals/new'
    | '/buyer/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BuyerRoute: typeof BuyerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/deals': {
      id: '/buyer/deals'
      path: '/deals'
      fullPath: '/buyer/deals'
      preLoaderRoute: typeof BuyerDealsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/dashboard': {
      id: '/buyer/dashboard'
      path: '/dashboard'
      fullPath: '/buyer/dashboard'
      preLoaderRoute: typeof BuyerDashboardRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/clients': {
      id: '/buyer/clients'
      path: '/clients'
      fullPath: '/buyer/clients'
      preLoaderRoute: typeof BuyerClientsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/supermarkets': {
      id: '/admin/supermarkets'
      path: '/supermarkets'
      fullPath: '/admin/supermarkets'
      preLoaderRoute: typeof AdminSupermarketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/buyer/deals/': {
      id: '/buyer/deals/'
      path: '/'
      fullPath: '/buyer/deals/'
      preLoaderRoute: typeof BuyerDealsIndexRouteImport
      parentRoute: typeof BuyerDealsRoute
    }
    '/buyer/deals/new': {
      id: '/buyer/deals/new'
      path: '/new'
      fullPath: '/buyer/deals/new'
      preLoaderRoute: typeof BuyerDealsNewRouteImport
      parentRoute: typeof BuyerDealsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDealsRoute: typeof AdminDealsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSupermarketsRoute: typeof AdminSupermarketsRoute
  AdminTeamRoute: typeof AdminTeamRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDealsRoute: AdminDealsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSupermarketsRoute: AdminSupermarketsRoute,
  AdminTeamRoute: AdminTeamRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BuyerDealsRouteChildren {
  BuyerDealsNewRoute: typeof BuyerDealsNewRoute
  BuyerDealsIndexRoute: typeof BuyerDealsIndexRoute
}

const BuyerDealsRouteChildren: BuyerDealsRouteChildren = {
  BuyerDealsNewRoute: BuyerDealsNewRoute,
  BuyerDealsIndexRoute: BuyerDealsIndexRoute,
}

const BuyerDealsRouteWithChildren = BuyerDealsRoute._addFileChildren(
  BuyerDealsRouteChildren,
)

interface BuyerRouteChildren {
  BuyerClientsRoute: typeof BuyerClientsRoute
  BuyerDashboardRoute: typeof BuyerDashboardRoute
  BuyerDealsRoute: typeof BuyerDealsRouteWithChildren
}

const BuyerRouteChildren: BuyerRouteChildren = {
  BuyerClientsRoute: BuyerClientsRoute,
  BuyerDashboardRoute: BuyerDashboardRoute,
  BuyerDealsRoute: BuyerDealsRouteWithChildren,
}

const BuyerRouteWithChildren = BuyerRoute._addFileChildren(BuyerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BuyerRoute: BuyerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
